### ISSUE TITLE
Reuse configuration in gui.

### ISSUE THREAD

**Issue by turiot** [harp077/pj-ftp-server#1]
Hello,

Could you add a feature to backup/restore configuration (host, user, directory) in gui mode, mainly for running many times the application without retyping settings ?
I would do it myself, but lack of time for the moment.

And thanks again for pjl (launched at linux startup), it changed my life.

Thank you and very friendly regards.

**Comment by harp077** [comment]
Good day, Thierry !
I will do it later.
Many thanks !
With best regards,
Roman

**Comment by harp077** [comment]
I made it)

**Comment by turiot** [comment]
Hello Roman,
It works fine !
Thanks a lot,
Thierry

**Comment by harp077** [comment]
Good day, Thierry ! 
How are you ?

With best regards, Roman = coldrom2017@gmail.com
